apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort # default type is ClusterIP . NodePort and LoadBalancer are other types
  selector:
    app: nginx
  ports:
    - port: 8082 # service port any port  (for Node Port :30000-32767)
      targetPort: 80 #  container port
      nodePort: 30000 # 30000-32767
